version: '3'
services:

  nest-service:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./.production.env
    ports:
      - 8080:8080

  postgres-db:
    image: postgres
    env_file:
      - ./.production.env
    ports:
      - 5432:5432